global One
global Two
global Three
global Four
global Five
global Six
global Seven
global Eight
global Nine

global OneZero  
global OneOne  
global OneTwo  
global OneThree  
global OneFour  
global OneFive
global OneSix  
global OneSeven  
global OneEight  
global OneNine  

global TwoZero  
global TwoOne  
global TwoTwo  
global TwoThree  
global TwoFour  
global TwoFive  
global TwoSix  
global TwoSeven  
global TwoEight  
global TwoNine  

global ThreeZero  
global ThreeOne  
global ThreeTwo  
global ThreeThree  
global ThreeFour  
global ThreeFive  
global ThreeSix  
global ThreeSeven  
global ThreeEight  
global ThreeNine  

global FourZero  
global FourOne  
global FourTwo  
global FourThree  
global FourFour  
global FourFive  
global FourSix  
global FourSeven  
global FourEight  
global FourNine  

global FiveZero  
global FiveOne  
global FiveTwo  
global FiveThree  
global FiveFour  
global FiveFive  
global FiveSix  
global FiveSeven  
global FiveEight  
global SixZero  
global FiveNine  

global SixZero  
global SixOne  
global SixTwo  
global SixThree  
global SixFour  
global SixFive  
global SixSix  
global SixSeven  
global SixEight  
global SixNine  

global SevenZero  
global SevenOne  
global SevenTwo  
global SevenThree  
global SevenFour  
global SevenFive  
global SevenSix  
global SevenSeven  
global SevenEight  
global SevenNine  

global EightZero  
global EightOne  
global EightTwo  
global EightThree  
global EightFour  
global EightFive  
global EightSix  
global EightSeven  
global EightEight  
global EightNine  

global NineZero  
global NineOne  
global NineTwo  
global NineThree  
global NineFour  
global NineFive  
global NineSix  
global NineSeven  
global NineEight  
global NineNine  

global OneZeroZero  
global OneZeroOne  
global OneZeroTwo  
global OneZeroThree  
global OneZeroFour  
global OneZeroFive  
global OneZeroSix  
global OneZeroSeven  
global OneZeroEight  
global OneZeroNine  

global OneOneZero  
global OneOneOne  
global OneOneTwo  
global OneOneThree  
global OneOneFour  
global OneOneFive  
global OneOneSix  
global OneOneSeven  
global OneOneEight  
global OneOneNine  

global OneTwoZero  
global OneTwoOne  
global OneTwoTwo  
global OneTwoThree  
global OneTwoFour  
global OneTwoFive  
global OneTwoSix  
global OneTwoSeven  
global OneTwoEight  
global OneTwoNine  

global OneThreeZero  
global OneThreeOne  
global OneThreeTwo  
global OneThreeThree  
global OneThreeFour  
global OneThreeFive  
global OneThreeSix  
global OneThreeSeven  
global OneThreeEight  
global OneThreeNine  

global OneFourZero  
global OneFourOne  
global OneFourTwo  
global OneFourThree  
global OneFourFour  
global OneFourFive  
global OneFourSix  
global OneFourSeven  
global OneFourEight  
global OneFourNine  

global OneFiveZero  
global OneFiveOne  
global OneFiveTwo  
global OneFiveThree  
global OneFiveFour  
global OneFiveFive  
global OneFiveSix  
global OneFiveSeven  
global OneFiveEight  
global OneFiveNine  

global OneSixZero  
global OneSixOne  
global OneSixTwo  
global OneSixThree  
global OneSixFour  
global OneSixFive  
global OneSixSix  
global OneSixSeven  
global OneSixEight  
global OneSixNine  

global OneSevenZero  
global OneSevenOne  
global OneSevenTwo  
global OneSevenThree  
global OneSevenFour  
global OneSevenFive  
global OneSevenSix  
global OneSevenSeven  
global OneSevenEight  
global OneSevenNine  

global OneEightZero  
global OneEightOne  
global OneEightTwo  
global OneEightThree  
global OneEightFour  
global OneEightFive  
global OneEightSix  
global OneEightSeven  
global OneEightEight  
global OneEightNine  

global OneNineZero  
global OneNineOne  
global OneNineTwo  
global OneNineThree  
global OneNineFour  
global OneNineFive  
global OneNineSix  
global OneNineSeven  
global OneNineEight  
global OneNineNine  

global TwoZeroZero  
global TwoZeroOne  
global TwoZeroTwo  
global TwoZeroThree  
global TwoZeroFour  
global TwoZeroFive  
global TwoZeroSix  
global TwoZeroSeven  
global TwoZeroEight  
global TwoZeroNine  

global TwoOneZero  
global TwoOneOne  
global TwoOneTwo  
global TwoOneThree  
global TwoOneFour  
global TwoOneFive  
global TwoOneSix  
global TwoOneSeven  
global TwoOneEight  
global TwoOneNine  

global TwoTwoZero  
global TwoTwoOne  
global TwoTwoTwo  
global TwoTwoThree  
global TwoTwoFour  
global TwoTwoFive  
global TwoTwoSix  
global TwoTwoSeven  
global TwoTwoEight  
global TwoTwoNine  

global TwoThreeZero  
global TwoThreeOne  
global TwoThreeTwo  
global TwoThreeThree  
global TwoThreeFour  
global TwoThreeFive  
global TwoThreeSix  
global TwoThreeSeven  
global TwoThreeEight  
global TwoThreeNine  

global TwoFourZero  
global TwoFourOne  
global TwoFourTwo  
global TwoFourThree  
global TwoFourFour  
global TwoFourFive  
global TwoFourSix  
global TwoFourSeven  
global TwoFourEight  
global TwoFourNine  

global TwoFiveZero
global TwoFiveOne  
global TwoFiveTwo  
global TwoFiveThree  
global TwoFiveFour  
global TwoFiveFive  
global TwoFiveSix  
global TwoFiveSeven  
global TwoFiveEight  
global TwoFiveNine  

global TwoSixZero  
global TwoSixOne  
global TwoSixTwo  
global TwoSixThree  
global TwoSixFour  
global TwoSixFive  
global TwoSixSix  
global TwoSixSeven  
global TwoSixEight  
global TwoSixNine  

global TwoSevenZero  
global TwoSevenOne  
global TwoSevenTwo  
global TwoSevenThree  
global TwoSevenFour  
global TwoSevenFive  
global TwoSevenSix  
global TwoSevenSeven  
global TwoSevenEight  
global TwoSevenNine  

global TwoEightZero  
global TwoEightOne  
global TwoEightTwo  
global TwoEightThree  
global TwoEightFour  
global TwoEightFive  
global TwoEightSix  
global TwoEightSeven  
global TwoEightEight  
global TwoEightNine  

global TwoNineZero  
global TwoNineOne  
global TwoNineTwo  
global TwoNineThree  
global TwoNineFour  
global TwoNineFive  
global TwoNineSix  
global TwoNineSeven  
global TwoNineEight  
global TwoNineNine  

global ThreeZeroZero  
global ThreeZeroOne  
global ThreeZeroTwo  
global ThreeZeroThree  
global ThreeZeroFour  
global ThreeZeroFive  
global ThreeZeroSix  
global ThreeZeroSeven  
global ThreeZeroEight  
global ThreeZeroNine  

global ThreeOneZero  
global ThreeOneOne  
global ThreeOneTwo  
global ThreeOneThree  
global ThreeOneFour  
global ThreeOneFive  
global ThreeOneSix  
global ThreeOneSeven  
global ThreeOneEight  
global ThreeOneNine  

global ThreeTwoZero  
global ThreeTwoOne  
global ThreeTwoTwo  
global ThreeTwoThree  
global ThreeTwoFour  
global ThreeTwoFive  
global ThreeTwoSix  
global ThreeTwoSeven  
global ThreeTwoEight  
global ThreeTwoNine  

global ThreeThreeZero  
global ThreeThreeOne   
global ThreeThreeTwo  
global ThreeThreeThree  
global ThreeThreeFour  
global ThreeThreeFive  
global ThreeThreeSix  
global ThreeThreeSeven  
global ThreeThreeEight  
global ThreeThreeNine  

global ThreeFourZero  
global ThreeFourOne  
global ThreeFourTwo  
global ThreeFourThree  
global ThreeFourFour  
global ThreeFourFive  
global ThreeFourSix  
global ThreeFourSeven  
global ThreeFourEight  
global ThreeFourNine  

global ThreeFiveZero  
global ThreeFiveOne  
global ThreeFiveTwo  
global ThreeFiveThree  
global ThreeFiveFour  
global ThreeFiveFive  
global ThreeFiveSix  
global ThreeFiveSeven  
global ThreeFiveEight  
global ThreeFiveNine  

global ThreeSixZero  
global ThreeSixOne  
global ThreeSixTwo  
global ThreeSixThree  
global ThreeSixFour  
global ThreeSixFive  
global ThreeSixSix  
global ThreeSixSeven  
global ThreeSixEight  
global ThreeSixNine  

global ThreeSevenZero  
global ThreeSevenOne  
global ThreeSevenTwo  
global ThreeSevenThree  
global ThreeSevenFour  
global ThreeSevenFive  
global ThreeSevenSix  
global ThreeSevenSeven  
global ThreeSevenEight  
global ThreeSevenNine  

global ThreeEightZero  
global ThreeEightOne  
global ThreeEightTwo  
global ThreeEightThree  
global ThreeEightFour  
global ThreeEightFive  
global ThreeEightSix  
global ThreeEightSeven  
global ThreeEightEight  
global ThreeEightNine  

global ThreeNineZero  
global ThreeNineOne  
global ThreeNineTwo  
global ThreeNineThree  
global ThreeNineFour  
global ThreeNineFive  
global ThreeNineSix  
global ThreeNineSeven  
global ThreeNineEight  
global ThreeNineNine  

global FourZeroZero  
global FourZeroOne  
global FourZeroTwo  
global FourZeroThree  
global FourZeroFour  
global FourZeroFive  
global FourZeroSix  
global FourZeroSeven  
global FourZeroEight  
global FourZeroNine  

global FourOneZero  
global FourOneOne  
global FourOneTwo  
global FourOneThree  
global FourOneFour  
global FourOneFive  
global FourOneSix  
global FourOneSeven  
global FourOneEight  
global FourOneNine  

global FourTwoZero  
global FourTwoOne  
global FourTwoTwo  
global FourTwoThree  
global FourTwoFour  
global FourTwoFive  
global FourTwoSix  
global FourTwoSeven  
global FourTwoEight  
global FourTwoNine  

global FourThreeZero  
global FourThreeOne  
global FourThreeTwo  
global FourThreeThree  
global FourThreeFour  
global FourThreeFive  
global FourThreeSix  
global FourThreeSeven  
global FourThreeEight  
global FourThreeNine  

global FourFourZero  
global FourFourOne  
global FourFourTwo  
global FourFourThree  
global FourFourFour  
global FourFourFive  
global FourFourSix  
global FourFourSeven  
global FourFourEight  
global FourFourNine  

global FourFiveZero  
global FourFiveOne  
global FourFiveTwo  
global FourFiveThree  
global FourFiveFour   
global FourFiveFive  
global FourFiveSix  
global FourFiveSeven  
global FourFiveEight  
global FourFiveNine  

global FourSixZero  
global FourSixOne  
global FourSixTwo  
global FourSixThree  
global FourSixFour  
global FourSixFive  
global FourSixSix  
global FourSixSeven  
global FourSixEight  
global FourSixNine  

global FourSevenZero  
global FourSevenOne  
global FourSevenTwo  
global FourSevenThree  
global FourSevenFour  
global FourSevenFive  
global FourSevenSix  
global FourSevenSeven  
global FourSevenEight  
global FourSevenNine   

global FourEightZero  
global FourEightOne  
global FourEightTwo  
global FourEightThree  
global FourEightFour  
global FourEightFive  
global FourEightSix  
global FourEightSeven  
global FourEightEight  
global FourEightNine  

global FourNineZero  
global FourNineOne  
global FourNineTwo  
global FourNineThree  
global FourNineFour  
global FourNineFive  
global FourNineSix  
global FourNineSeven  
global FourNineEight  
global FourNineNine  

global FiveZeroZero  
global FiveZeroOne  
global FiveZeroTwo  
global FiveZeroThree  
global FiveZeroFour  
global FiveZeroFive  
global FiveZeroSix  
global FiveZeroSeven  
global FiveZeroEight  
global FiveZeroNine  

global FiveOneZero  
global FiveOneOne  
global FiveOneTwo  
global FiveOneThree  
global FiveOneFour  
global FiveOneFive  
global FiveOneSix  
global FiveOneSeven  
global FiveOneEight  
global FiveOneNine  

global FiveTwoZero  
global FiveTwoOne  
global FiveTwoTwo  
global FiveTwoThree  
global FiveTwoFour  
global FiveTwoFive  
global FiveTwoSix  
global FiveTwoSeven  
global FiveTwoEight  
global FiveTwoNine  

global FiveThreeZero  
global FiveThreeOne  
global FiveThreeTwo  
global FiveThreeThree  
global FiveThreeFour  
global FiveThreeFive  
global FiveThreeSix  
global FiveThreeSeven  
global FiveThreeEight  
global FiveThreeNine  

global FiveFourZero  
global FiveFourOne  
global FiveFourTwo  
global FiveFourThree  
global FiveFourFour  
global FiveFourFive  
global FiveFourSix  
global FiveFourSeven  
global FiveFourEight  
global FiveFourNine  

global FiveFiveZero  
global FiveFiveOne  
global FiveFiveTwo  
global FiveFiveThree  
global FiveFiveFour  
global FiveFiveFive  
global FiveFiveSix  
global FiveFiveSeven  
global FiveFiveEight  
global FiveFiveNine  

global FiveSixZero  
global FiveSixOne  
global FiveFiveSixTwo  
global FiveSixThree  
global FiveSixFour  
global FiveSixFive  
global FiveSixSix  
global FiveSixSeven  
global FiveSixEight  
global FiveSixNine  

global FiveSevenZero  
global FiveSevenOne  
global FiveSevenTwo  
global FiveSevenThree  
global FiveSevenFour  
global FiveSevenFive  
global FiveSevenSix  
global FiveSevenSeven  
global FiveSevenEight  
global FiveSevenNine  

global FiveEightZero  
global FiveEightOne  
global FiveEightTwo  
global FiveEightThree  
global FiveEightFour  
global FiveEightFive  
global FiveEightSix  
global FiveEightSeven  
global FiveEightEight  
global FiveEightNine  

global FiveNineZero  
global FiveNineOne  
global FiveNineTwo  
global FiveNineThree  
global FiveNineFour  
global FiveNineFive  
global FiveNineSix  
global FiveNineSeven  
global FiveNineEight  
global FiveNineNine  

global SixZeroZero